### ISSUE TITLE
Cant see the metadata-osd

### ISSUE THREAD

**Issue by akash-258** [vc-01/metadata-osd#1]
Placed the lua file in scripts folder and conf file in script-opts folder. After playing some mp3 and mp4 files, I cant see any other osd other than the default one.

mpv.conf:
```
hwdec=auto-safe
volume=100
fs=yes
force-seekable=yes
cursor-autohide=200
sub-auto=fuzzy
cache=yes
demuxer-max-bytes=500M
demuxer-max-back-bytes=100M
ytdl-format="((bestvideo[height<=?1080][vcodec^=vp9]/bestvideo)+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio))/best"
ytdl-raw-options=yes-playlist=
script-opts=ytdl_hook-ytdl_path=/home/akash/.local/bin/yt-dlp

glsl-shaders = ""
glsl-shaders = "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"
```

Current scripts :
![mpv](https://user-images.githubusercontent.com/43058609/179345361-412514ad-c88b-4e55-9b46-30f3504150df.png)

Input.conf only has CTRL1 to CTRL5 binded to some shaders.

**Comment by vc-01** [comment]
I tested with the provided (yours) mpv config file but without the other plugins or shaders installed. There were no issues. This will be breaking together with the other scripts, I guess.

The metadata OSD should show up with no script's own config file (which is optional), since the default is to enable the OSD on start.

To test manually triggering the OSD, the script needs to have the main kill switch off (either by setting `enable_on_start=yes` (default) or whilst playing a media file in mpv pressing the key defined by the `key_toggleenable` option) and an actual key binding for triggering the OSD (the `key_toggleosd_1` option). So, with a config file defining just the binding key for triggering the OSD as e.g. to key _F11_:

```
key_toggleosd_1=F11
```

and opening the media file with debugging enabled for the metadata-osd script from command line:

`mpv --msg-level=metadata_osd=debug "<full_path_to_mediafile>"`

something might pop up in the terminal.  By pressing the _F11_ key in this case will trigger the function to show/hide the OSD, but I guess the issue is happening sooner during load.

> Input.conf only has CTRL1 to CTRL5 binded to some shaders.

Bindings defined in `input.conf` will be preferred over the ones defined in the script's own config file (the script is utilizing so called "weak" bindings). Still, I couldn't bind the mentioned keys:

`[input] Unknown key 'CTRL1' at ~/.config/mpv/input.conf:11`
`[input] Unknown key 'CTRL5' at ~/.config/mpv/input.conf:12`

Mpv's input key list doesn't list these (at least not on current Arch Linux' build):

```
$ mpv --input-keylist | grep CTRL
$ 
```

Also to mention, the "weak" key binding might or might no work if the binding is defined multiple times for multiple scripts; a random one will be chosen. From the manual page:

_Trying to map multiple commands to a key will essentially prefer a random binding, while the other bindings are not called._

**Comment by vc-01** [comment]
Please provide any debug output as suggested or try with clean _mpv.conf_ file. If something important is missing in the documentation, suggestions are welcomed.
Until then, _closing_ the issue.
