### ISSUE TITLE
config keybinds using `input.conf`

### ISSUE THREAD

**Issue by OmiChrome** [vc-01/metadata-osd#5]
i just want a way to configure keybinds using `input.conf` like :

`KEY script-message OPTIONS`

 i want this for purposes of my mpv can't read input's from `script-opts/*lua` coz i have blocked all the default key which include script-keys tooo :(

**Comment by vc-01** [comment]
This works in my setup:

``<key> script-message-to metadata_osd <message> ``

The following as well but the first approach is recommended since it sends the message only to the named script (or "target") not to all scripts (or "clients" from the documentation):

``<key> script-message <message>``

The message namespace is very script-centric. I would not recommend using 'script-message'.

One full example:

``F6 script-message-to metadata_osd toggle_osd_1``

The currently supported messages are searchable through the lua script as 'mp.add_key_binding' function call's second argument. This could go to the documentation in the future. I wasn't using or testing this approach yet.

**Comment by OmiChrome** [comment]
> The currently supported messages are searchable through the lua script as 'mp.add_key_binding' function

does it mean , not all keybinds are suported from [metadata_osd.conf](https://github.com/vc-01/metadata-osd/blob/main/script-opts/metadata_osd.conf)?



> One full example:
> 
> `F6 script-message-to metadata_osd toggle_osd_1`

this seeems to work thx!

**Comment by vc-01** [comment]
What do you mean by "all" keybindings? Metadata-osd scripts sets its own key bindings, those should be _all_ callable externally. They're just not documented yet, so you need search through the code to find out what you can call (or what message you can send, to be more exact), as e.g. you can send "toggle_osd_1". All bindings in the script have a defined message, so they should be callable.

The one message text I will probably change is "toggle_osd_autohide" to match with the config key to "toggle_autohide". So take it as unstable until it's published as a feature.

Plus, from the documentation, it seems more proper to use 'script-binding' to invoke a script's binding. For example:

``F6 script-binding metadata_osd/toggle_osd_1``

Better if you mention exactly what is not working, then I can check.

**Comment by vc-01** [comment]
TODO:
- [x]  Add support for setting key bindings in 'input.conf'

**Comment by OmiChrome** [comment]
> What do you mean by "all" keybindings?

just keybinds provided from metadata_osd.conf for metada_osd !

> probably change is "toggle_osd_autohide" to match with the config key to "toggle_autohide".

it will more easire to config then Thank you <3

**Comment by OmiChrome** [comment]
> mention exactly what is not working

i do had some problem , but i don't know wats that exctacly    , if see any agian i wll calll  ! thx

**Comment by vc-01** [comment]
>> What do you mean by "all" keybindings?

> just keybinds provided from metadata_osd.conf for metada_osd !

then the answer is yes, all of them -> will be documented.

**Comment by vc-01** [comment]
There were some renames in the latest commit, so check with the table in [Key Bindings](https://github.com/vc-01/metadata-osd#key-bindings) or the input.conf template below rather.
