### ISSUE TITLE
Debian Testing: failed to launch, probably because of LuaJit

### ISSUE THREAD

**Issue by tkapias** [vc-01/metadata-osd#6]
I have installed lua5.1 to 5.4 and luagit, with dev and lib packages.

But the addon fail to load.

1. First because it blocks on a unicode escaping : 

``` sh
[metadata_osd] Loading lua script /home/tomasz/.config/mpv/scripts/metadata_osd.lua...
[metadata_osd] loading mp.defaults
[metadata_osd] loading file /home/tomasz/.config/mpv/scripts/metadata_osd.lua
[metadata_osd] 
[metadata_osd] stack traceback:
[metadata_osd]  [C]: in ?
[metadata_osd]  [C]: in ?
[metadata_osd] Lua error: [string "/home/tomasz/.config/mpv/scripts/metadata_osd..."]:207: invalid escape sequence near '\u'
[metadata_osd] Exiting...
```

2. Then if I remove this string it fail to load a luagit module:

``` sh
[metadata_osd] Loading lua script /home/tomasz/.config/mpv/scripts/metadata_osd.lua...                                                           [65/313]
[metadata_osd] loading mp.defaults                                                                                                                       
[metadata_osd] loading file /home/tomasz/.config/mpv/scripts/metadata_osd.lua                                                                            
[metadata_osd] reading options for metadata-osd                                                                                                          
[metadata_osd] script-opts/metadata-osd.conf not found.                                                                                                  
[metadata_osd] lua-settings/metadata-osd.conf not found.                                                                                                 
[metadata_osd] reading options for metadata_osd                             
[metadata_osd] Opened config file script-opts/metadata_osd.conf. 
[metadata_osd] str_split_styleoption(): found: left_justified 
[metadata_osd] str_split_styleoption(): found: midtitle                                                                                                  
[metadata_osd] str_split_styleoption(): found: centered                                                                                                  
[metadata_osd] str_split_styleoption(): found: midtitle 
[metadata_osd] str_split_styleoption(): found: bold                                                                                                      
[metadata_osd] str_split_styleoption(): found: bold 
[metadata_osd] str_split_styleoption(): found: italic                                                                                                    [metadata_osd] ass_prepare_templates(): osd_1 template: {\a9}{\bord3}\N\N\N{\shad0}{\fscx100}{\fscy100}{\fsp0}{\b1}##TEXTAREA_1_STR##{\b0}\N{\shad0}{\fsc
x100}{\fscy100}{\fsp0}{\b1}##TEXTAREA_2_STR##{\b0}{\shad0}{\fscx100}{\fscy100}{\fsp0}##TEXTAREA_2_RELDATE_STR##\N\N\N{\shad1}{\fscx100}{\fscy100}{\fsp10}
{\i1}##TEXTAREA_3_STR##{\i0}\N\N\N\N{\shad0}{\fscx60}{\fscy60}{\fsp0}##TEXTAREA_4_STR## 
[metadata_osd] ass_prepare_templates(): osd_2 template: {\a10}{\bord3}\N\N\N{\shad0}{\fscx100}{\fscy100}{\fsp0}##TEXTAREA_1_STR##                        
[metadata_osd] 
[metadata_osd] stack traceback:                                                                                                                          
[metadata_osd]  [C]: in function 'require'
[metadata_osd]  [string "/home/tomasz/.config/mpv/scripts/metadata_osd..."]:1583: in main chunk
[metadata_osd]  [C]: in ?                                                                                                                                
[metadata_osd]  [C]: in ?                                                   
[metadata_osd] Lua error: [string "/home/tomasz/.config/mpv/scripts/metadata_osd..."]:1583: module 'ffi' not found:
[metadata_osd]  no field package.preload['ffi']                 
[metadata_osd]  no file '/usr/local/share/lua/5.2/ffi.lua'            
[metadata_osd]  no file '/usr/local/share/lua/5.2/ffi/init.lua'
[metadata_osd]  no file '/usr/local/lib/lua/5.2/ffi.lua'  
[metadata_osd]  no file '/usr/local/lib/lua/5.2/ffi/init.lua'           
[metadata_osd]  no file '/usr/share/lua/5.2/ffi.lua'
[metadata_osd]  no file '/usr/share/lua/5.2/ffi/init.lua'
[metadata_osd]  no file '/usr/local/lib/lua/5.2/ffi.so'
[metadata_osd]  no file '/usr/lib/x86_64-linux-gnu/lua/5.2/ffi.so'
[metadata_osd]  no file '/usr/lib/lua/5.2/ffi.so'
[metadata_osd]  no file '/usr/local/lib/lua/5.2/loadall.so'
[metadata_osd] Exiting...
```

Apparently LuaJit stayed stuck at lua5.1, I tried to forc my system to use lua5.2 executable but the MPV log still output 5.2 paths in the error log.

I am new to lua ecosystem so I may miss something obvious.

**Comment by vc-01** [comment]
Thanks for the nice bug report! Yes, It is not obvious on the first sight what is supported and what is not in the case of Lua version mpv links with, which is really LuaJIT binary. It is that LuaJIT as you mentioned is stuck to Lua 5.1 but with some extensions took from Lua 5.2 plus with theirs own. This bug will be probably related to the LuaJIT build Debian packagers are distributing.

I'm surely willing to fix this and make the script more "runnable".

We can get rid of the unicode ellipsis character and replace it with three dots - no problem. 

To the second part, believe it or not, I discovered the 'ffi' requirement as a remnant from the past and deleted it in my local copy about 20 minutes before you filed the bug. :)

'ffi' is not being used by the script, the line can be just removed:

https://github.com/vc-01/metadata-osd/blob/44cd4ba025d276f68894a1d6f3cef071de419dbb/scripts/metadata_osd.lua#L1583

I have this change staged locally already.

I thought since LuaJIT is not changing much, I could rely on every feature they offer. Apparently this depends build per build. 

About forcing using mpv to use this or that Lua version, this is probably not possible, but only investigating into mpv project directly would tell. From the other point of view, this is an advantage.

For the ellipsis character, this can be set to empty string or three dots "..." for the testing:
https://github.com/vc-01/metadata-osd/blob/44cd4ba025d276f68894a1d6f3cef071de419dbb/scripts/metadata_osd.lua#L207

I will push the fix very soon.

**Comment by tkapias** [comment]
Thank you, I can use your script now.

But there was still an error with the last part:

``` bash
[metadata_osd] 
[metadata_osd] stack traceback:
[metadata_osd]  [string "/home/tomasz/.config/mpv/scripts/metadata_osd..."]:1597: in main chunk
[metadata_osd]  [C]: in ?
[metadata_osd]  [C]: in ?
[metadata_osd] Lua error: [string "/home/tomasz/.config/mpv/scripts/metadata_osd..."]:1597: attempt to index global 'jit' (a nil value)
```
I just deleted the if and it works for me.

``` diff
1,4c1
< if jit.os == "Linux" then
<     charencode_utf8 = true  -- UTF-8 is _assumed_,
<                             -- not querried from the system
< end
---
> charencode_utf8 = true
```

Maybe that it has to do with the debian build of mpv?

``` sh
OS: Debian GNU/Linux bookworm/sid x86_64 
Kernel: 6.0.0-2-amd64 
Shell: bash 5.2.2 
DE: lightdm-xsession 
WM: i3 
Terminal: tmux 

mpv: 0.34.1 
LuaJIT: 2.1.0-beta3
Lua: 5.2.4 (5.1/3/4 available too)
```

**Comment by vc-01** [comment]
Thank you again for your time looking into this. I assumed wrongly that LuaJIT is another "write once run everywhere" platform. :) I haven't tested the script on different Linux distribution let aside Windows. Seems I might consider doing it (sooner than later).

FYI, I'm running this script on latest Arch Linux, following are my package versions:
```
Kernel: 6.0.2-arch1-1
mpv: 1:0.34.1-5
LuaJIT: 2.1.0.beta3.r449.gdad04f17-1
Lua: 5.1.5-9
```

I believe the standalone Lua version is not important here since mpv is linked only with LuaJIT which is self-contained:
```
$ ldd $(which mpv) | grep -i lua
        libluajit-5.1.so.2 => /usr/lib/libluajit-5.1.so.2 (0x00007f1e0e370000)
$ ldd /usr/lib/libluajit-5.1.so.2
        linux-vdso.so.1 (0x00007ffc05fa2000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f1cf1c1c000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f1cf1bfc000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f1cf1a15000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f1cf1db9000)
```
To your questions:
> I am new to lua ecosystem so I may miss something obvious.

The situation is surely not obvious.

> I just deleted the if and it works for me.

Yes, this is a stable working solution for Linux in general.

> Maybe that it has to do with the debian build of mpv?

I will investigate into this. Debian, including Testing is a reference platform, it needs to run there.

_Waiting_: I will keep this issue open, until I will come with some results and fixes.

**Comment by vc-01** [comment]
Everything from above is easily answered by a fact that mpv is linked against Lua not LuaJIT on Debian Testing.

```
$ ldd $(which mpv) | grep lua
        liblua5.2.so.0 => /lib/x86_64-linux-gnu/liblua5.2.so.0 (0x00007efdaf9e3000)

$ dpkg-query --search liblua5.2.so.0
liblua5.2-0:amd64: /usr/lib/x86_64-linux-gnu/liblua5.2.so.0

$ dpkg-query --status liblua5.2-0:amd64 | grep Homepage
Homepage: https://www.lua.org
```

I will eventually come up with some different OS detection mechanism to enable UTF-8 string operations.

Plus, the font on Debian looks quite ugly in mpv.

The last patch might be closing this issue, others will be solved separately.
