### ISSUE TITLE
How do I display metadata in following format?

### ISSUE THREAD

**Issue by WhoMI7** [vc-01/metadata-osd#9]
Similar to this
With path not being displayed
![image](https://user-images.githubusercontent.com/93109835/223706299-1b63a5d2-049d-49d5-9c6f-4471102c1c90.png)

I don't want it to display like this :
![image](https://user-images.githubusercontent.com/93109835/223707077-ff8e0e28-97cb-4698-87ab-f38daacbf5e6.png)

If there's no artist or album metadata it should just not show path instead.

**Comment by OmiChrome** [comment]
bro use any audio tagger 
https://picard.musicbrainz.org/

**Comment by WhoMI7** [comment]
> bro use any audio tagger https://picard.musicbrainz.org/

I didn't ask for a audio tagger recommendation.
I just don't like it displaying path when metadata is not available.

**Comment by OmiChrome** [comment]
okay wait for author then

**Comment by vc-01** [comment]
Firstly, you have reported a bug along with the request, which I'm thanking you for. I will explain; the default behavior of the script if there's no album and/or artist metadata present is to show folder name of the currently playing song and folder name one above in path hierarchy - a fallback solution showing something closer to useful than nothing. I don't use this script on Windows and this has not been tested I think at all. Forward '/' and backward slashes '\\' are visibly broken from the screenshot - I will fix this.

Secondly, if you will find this fallback solution still a bad idea, it is possible to adjust or disable it. For example to show nothing instead of the folder names (as requested) add the following to your script's configuration file:

```
gsub_text_area_1_fallback_pattern_1=.*
gsub_text_area_1_fallback_repl_1=
gsub_text_area_2_fallback_pattern_1=.*
gsub_text_area_2_fallback_repl_1=
```

See [README.md](https://github.com/vc-01/metadata-osd#installation--configuration) for how to set up the configuration file.

_Note_: This fallback approach is also active for the third field (or title metadata if present) in which case, file name is the starting point which can be further processed. By default it already is.

**Comment by vc-01** [comment]
@BhaturaGuy: The latest commit 0a379f82dff398b303bb831c62183b2e0bd13e1e is fixing the issues with back slashes in path. I will close this already but feel free to add comments if anything.

**Comment by WhoMI7** [comment]
> ```
>gsub_text_area_1_fallback_pattern_1=.*
>gsub_text_area_1_fallback_repl_1=
>gsub_text_area_2_fallback_pattern_1=.*
>gsub_text_area_2_fallback_repl_1=
>```

This worked like a charm. Thank you.
